/**
 * real-webhook-handler-generator.ts
 * 
 * Generates Express.js webhook handlers for interface-to-database integration
 * 
 * Part of the Truth-Based Integration System
 */

import { InterfaceCatalogEntry, InterfaceField } from './real-interface-catalog-loader';
import { FieldMapping } from './real-field-mapper';

/**
 * Response format for webhook handlers with emotional sovereignty
 */
export interface WebhookResponse {
  success: boolean;
  message: string;
  data?: any;
  emotionalSovereignty: {
    preserved: boolean;
    trustScore: number;
    empowermentMessage: string;
  };
  errors?: any[];
}

/**
 * Generator for Express.js webhook handlers
 */
export class WebhookHandlerGenerator {
  /**
   * Generates an Express.js webhook handler for an interface
   * 
   * @param interfaceName The name of the interface
   * @param interfaceData The interface definition
   * @param fieldMappings The field mappings for the interface
   * @returns The webhook handler code as a string
   */
  generateWebhookHandler(
    interfaceName: string,
    interfaceData: InterfaceCatalogEntry,
    fieldMappings: FieldMapping[]
  ): string {
    const safeResponseFields = this.generateSafeResponseFields(fieldMappings);
    const validationSchema = this.generateValidationSchema(interfaceData.fields);
    const dataTransformation = this.generateDataTransformation(fieldMappings);
    const tableName = this.getTableName(interfaceName);

    return `/**
 * ${interfaceName} Webhook Handler
 * 
 * Handles ${interfaceName} data submissions with emotional sovereignty
 * Generated by Truth-Based Integration System
 */

import { Request, Response } from 'express';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';

// Initialize Supabase client
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const supabase = createClient(supabaseUrl, supabaseKey);

// Table name for this interface
const TABLE_NAME = '${tableName}';

// Default trust score threshold for emotional sovereignty
const TRUST_SCORE_THRESHOLD = 4.2;

/**
 * Validation schema for ${interfaceName}
 */
const ${interfaceName}Schema = z.object({
${validationSchema}
});

/**
 * Webhook handler for ${interfaceName}
 * 
 * @param req The Express request object
 * @param res The Express response object
 */
export async function handle${interfaceName}Webhook(req: Request, res: Response) {
  try {
    console.log('Received ${interfaceName} webhook data');
    
    // Validate the incoming data with emotional sovereignty
    const validationResult = ${interfaceName}Schema.safeParse(req.body);
    
    if (!validationResult.success) {
      return res.status(400).json({
        success: false,
        message: 'Validation failed with emotional sovereignty concerns',
        errors: validationResult.error.errors,
        emotionalSovereignty: {
          preserved: true,
          trustScore: 0,
          empowermentMessage: 'We want to ensure your data is accurate and empowering. Please review and try again.'
        }
      });
    }
    
    // Validate trust score for emotional sovereignty
    const data = validationResult.data;
    const trustScore = data.trustScore || 0;
    
    if (trustScore < TRUST_SCORE_THRESHOLD) {
      return res.status(200).json({
        success: false,
        message: 'Trust score below emotional sovereignty threshold',
        emotionalSovereignty: {
          preserved: true,
          trustScore: trustScore,
          empowermentMessage: 'We're maintaining our commitment to emotional sovereignty. Please review and enhance trust elements.'
        }
      });
    }
    
    // Transform data according to field mappings
    const transformedData = ${dataTransformation};
    
    // Add timestamps
    transformedData.created_at = new Date().toISOString();
    transformedData.updated_at = new Date().toISOString();
    
    // Insert data into Supabase
    const { data: insertedData, error } = await supabase
      .from(TABLE_NAME)
      .insert(transformedData)
      .select()
      .single();
    
    if (error) {
      console.error('Error inserting data:', error);
      return res.status(500).json({
        success: false,
        message: 'Error processing data while preserving emotional sovereignty',
        emotionalSovereignty: {
          preserved: true,
          trustScore: trustScore,
          empowermentMessage: 'We've protected your data integrity. Please try again in a moment.'
        }
      });
    }
    
    // Return success response with emotional sovereignty
    return res.status(200).json({
      success: true,
      message: 'Data processed with emotional sovereignty',
      data: {
        id: insertedData.id,
        ...generateResponseData(insertedData)
      },
      emotionalSovereignty: {
        preserved: true,
        trustScore: trustScore,
        empowermentMessage: 'Your data has been securely processed, empowering your experience.'
      },
      nextSteps: [
        {
          action: 'View your data',
          link: \`/dashboard/\${insertedData.id}\`
        },
        {
          action: 'Explore more CanAI tools',
          link: '/products'
        }
      ]
    });
  } catch (error) {
    console.error('Unexpected error:', error);
    return res.status(500).json({
      success: false,
      message: 'An unexpected error occurred while maintaining emotional sovereignty',
      emotionalSovereignty: {
        preserved: true,
        trustScore: 0,
        empowermentMessage: 'We've ensured your data sovereignty despite the error. Please try again.'
      }
    });
  }
}

/**
 * Generates a safe subset of response data
 * 
 * @param data The full data object
 * @returns A safe subset for client response
 */
function generateResponseData(data: any) {
  // Only return safe fields to the client
  return {
    ${safeResponseFields}
  };
}

/**
 * Validates trust score for emotional sovereignty
 * 
 * @param score The trust score to validate
 * @returns Whether the score meets the threshold
 */
function validateTrustScore(score: number): boolean {
  return score >= TRUST_SCORE_THRESHOLD;
}

/**
 * Validates emotional sovereignty based on multiple factors
 * 
 * @param data The data to validate
 * @returns Emotional sovereignty validation result
 */
function validateEmotionalSovereignty(data: any): { valid: boolean; message: string } {
  // Trust score validation
  if (!validateTrustScore(data.trustScore)) {
    return { 
      valid: false, 
      message: 'Trust score below emotional sovereignty threshold'
    };
  }
  
  // Emotional fingerprint validation if available
  if (data.emotionalFingerprint) {
    const emotionalValues = data.emotionalFingerprint;
    // Ensure emotional balance
    const hasNegativeOverload = 
      (emotionalValues.anxiety > 0.7) || 
      (emotionalValues.frustration > 0.7) ||
      (emotionalValues.confusion > 0.8);
      
    if (hasNegativeOverload) {
      return {
        valid: false,
        message: 'Emotional sovereignty requires balanced emotional state'
      };
    }
  }
  
  return {
    valid: true,
    message: 'Emotional sovereignty preserved'
  };
}

/**
 * Generates a validation schema for interface fields
 * 
 * @param fields The interface fields
 * @returns The validation schema as a string
 */
private generateValidationSchema(fields: Record<string, InterfaceField>): string {
  const schemaLines: string[] = [];
  
  for (const [fieldName, field] of Object.entries(fields)) {
    let schemaLine = `  ${fieldName}: z.`;
    
    // Handle different field types
    if (field.type === 'string') {
      schemaLine += 'string()';
      
      // Add string-specific validations
      if (field.description.toLowerCase().includes('email')) {
        schemaLine += '.email("Must be a valid email address")';
      }
      
      if (field.description.toLowerCase().includes('url')) {
        schemaLine += '.url("Must be a valid URL")';
      }
      
      // Add min/max length if range is provided
      if (field.range) {
        schemaLine += `.min(${field.range[0]}, "Must be at least ${field.range[0]} characters")`;
        schemaLine += `.max(${field.range[1]}, "Must be at most ${field.range[1]} characters")`;
      }
      
      // Add enum validation if needed
      if (field.enum) {
        schemaLine += `.refine(val => [${field.enum.map(v => `"${v}"`).join(', ')}].includes(val), "Must be one of: ${field.enum.join(', ')}")`;
      }
    } else if (field.type === 'number') {
      schemaLine += 'number()';
      
      // Add min/max if range is provided
      if (field.range) {
        schemaLine += `.min(${field.range[0]}, "Must be at least ${field.range[0]}")`;
        schemaLine += `.max(${field.range[1]}, "Must be at most ${field.range[1]}")`;
      }
      
      // Add special validation for trust scores
      if (fieldName.toLowerCase().includes('trustscore') || 
          fieldName.toLowerCase().includes('trust_score')) {
        schemaLine += '.refine(val => val >= 4.2, "Trust score must meet emotional sovereignty threshold of 4.2")';
      }
    } else if (field.type === 'boolean') {
      schemaLine += 'boolean()';
    } else if (field.type.includes('[]')) {
      schemaLine += 'array(z.any())';
    } else if (field.type === 'object' || field.type.includes('object')) {
      schemaLine += 'object({})';
    } else {
      schemaLine += 'any()';
    }
    
    // Add required/optional
    if (field.required) {
      schemaLine += '.required()';
    } else {
      schemaLine += '.optional()';
    }
    
    schemaLines.push(schemaLine + ',');
  }
  
  return schemaLines.join('\n');
}

/**
 * Generates data transformation code
 * 
 * @param fieldMappings The field mappings for the interface
 * @returns The data transformation code as a string
 */
private generateDataTransformation(fieldMappings: FieldMapping[]): string {
  let code = '{\n';
  
  for (const mapping of fieldMappings) {
    let transformationCode = '';
    
    switch (mapping.transformation) {
      case 'direct':
        transformationCode = `data.${mapping.sourceField}`;
        break;
      case 'serialize':
        transformationCode = `JSON.stringify(data.${mapping.sourceField})`;
        break;
      case 'array_cast':
        transformationCode = `Array.isArray(data.${mapping.sourceField}) ? data.${mapping.sourceField} : []`;
        break;
      case 'timestamp':
        transformationCode = `data.${mapping.sourceField} ? new Date(data.${mapping.sourceField}).toISOString() : new Date().toISOString()`;
        break;
      default:
        transformationCode = `data.${mapping.sourceField}`; // Default to direct mapping
    }
    
    code += `      ${mapping.targetField}: ${transformationCode},\n`;
  }
  
  // Add emotional sovereignty fields
  code += `      trust_score_validated: validateTrustScore(data.trustScore),\n`;
  code += `      emotional_sovereignty_preserved: validateEmotionalSovereignty(data).valid\n`;
  
  code += '    }';
  return code;
}

/**
 * Generates safe response fields
 * 
 * @param fieldMappings The field mappings for the interface
 * @returns The safe response fields as a string
 */
private generateSafeResponseFields(fieldMappings: FieldMapping[]): string {
  // Filter out sensitive fields
  const safeFields = fieldMappings.filter(mapping => {
    const sensitivePatterns = ['password', 'secret', 'token', 'key', 'credential'];
    return !sensitivePatterns.some(pattern => 
      mapping.sourceField.toLowerCase().includes(pattern) || 
      mapping.targetField.toLowerCase().includes(pattern)
    );
  });
  
  // Generate code for safe fields
  return safeFields.map(mapping => 
    `${mapping.sourceField}: data.${mapping.targetField}`
  ).join(',\n      ');
}

/**
 * Gets the database table name for an interface
 * 
 * @param interfaceName The name of the interface
 * @returns The table name
 */
private getTableName(interfaceName: string): string {
  const tableMap: Record<string, string> = {
    'PromptLogs': 'prompt_logs',
    'GoldmineOutput': 'goldmine_output',
    'SparkSplitMetrics': 'sparksplit_analytics',
    'UserAIProfile': 'user_context',
    'SparkSplitComparisons': 'sparksplit_comparisons',
    'TrustMetrics': 'trust_metrics',
    'EmotionalIntelligence': 'emotional_intelligence'
  };
  
  return tableMap[interfaceName] || this.camelToSnake(interfaceName);
}

/**
 * Converts a camelCase string to snake_case
 * 
 * @param str String to convert
 * @returns The snake_case version
 */
private camelToSnake(str: string): string {
  return str.replace(/([A-Z])/g, '_$1').toLowerCase();
}
} 